ALTER TABLE LOG_ANALYZE_TOTAL_EVERY_TIME DROP FOREIGN KEY `LOG_ANALYZE_TOTAL_EVERY_TIME_ibfk_1` ;
ALTER TABLE log_table_history DROP FOREIGN KEY `channel_id` ;

ALTER TABLE MASTER_CHANNEL MODIFY `channel_id` TINYINT(2) not null ;
ALTER TABLE LOG_ANALYZE_RESOURCE MODIFY `channel_id` TINYINT(2) not null ;
ALTER TABLE LOG_ANALYZE_TOTAL_EVERY_TIME MODIFY `channel_id` TINYINT(2) not null ;
ALTER TABLE log_table_history MODIFY `channel_id` TINYINT(2) not null ;

ALTER TABLE log_table_history ADD FOREIGN KEY(channel_id) REFERENCES MASTER_CHANNEL(channel_id);
ALTER TABLE LOG_ANALYZE_RESOURCE ADD FOREIGN KEY(channel_id) REFERENCES MASTER_CHANNEL(channel_id);
ALTER TABLE LOG_ANALYZE_TOTAL_EVERY_TIME ADD FOREIGN KEY(channel_id) REFERENCES MASTER_CHANNEL(channel_id);
ALTER TABLE LOG_ANALYZE_TOTAL_EVERY_TIME MODIFY over_sec_type varchar(20) not null;

