CREATE TABLE `LOG_ANALYZE_AVG_EVERY_TIME` (
  `date_and_host` varchar(80) NOT NULL,
  `history_date` date NOT NULL,
  `channel_id` tinyint(2) NOT NULL,
  `total` float(11,6) unsigned default '0',
  `0` float(11,6) unsigned default '0',
  `1` float(11,6) unsigned default '0',
  `2` float(11,6) unsigned default '0',
  `3` float(11,6) unsigned default '0',
  `4` float(11,6) unsigned default '0',
  `5` float(11,6) unsigned default '0',
  `6` float(11,6) unsigned default '0',
  `7` float(11,6) unsigned default '0',
  `8` float(11,6) unsigned default '0',
  `9` float(11,6) unsigned default '0',
  `10` float(11,6) unsigned default '0',
  `11` float(11,6) unsigned default '0',
  `12` float(11,6) unsigned default '0',
  `13` float(11,6) unsigned default '0',
  `14` float(11,6) unsigned default '0',
  `15` float(11,6) unsigned default '0',
  `16` float(11,6) unsigned default '0',
  `17` float(11,6) unsigned default '0',
  `18` float(11,6) unsigned default '0',
  `19` float(11,6) unsigned default '0',
  `20` float(11,6) unsigned default '0',
  `21` float(11,6) unsigned default '0',
  `22` float(11,6) unsigned default '0',
  `23` float(11,6) unsigned default '0',
  PRIMARY KEY  (`date_and_host`),
  UNIQUE KEY `date_and_host` (`date_and_host`),
  KEY `channel_id` (`channel_id`),
  CONSTRAINT `LOG_ANALYZE_AVG_EVERY_TIME_ibfk_1` FOREIGN KEY (`channel_id`) REFERENCES `MASTER_CHANNEL` (`channel_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ;
